
name: Testing
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install eksctl
      run: |
        curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
        sudo mv /tmp/eksctl /usr/local/bin
        sleep 10
        eksctl version
        
    - name: Checkout code
      uses: actions/checkout@master
    
    - name: Run Shellcheck
      uses: bewuethr/shellcheck-action@v2
      
#     - name: Run golangci-lint
#       uses: actions-contrib/golangci-lint@v1

    # - name: Configure AWS credentials from secrets
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: us-east-2
    
    # - name: Install DOP on cluster
    #   run: |
    #     chmod +x ./utils/verify_dop_on_eks.sh
    #     ./utils/verify_dop_on_eks.sh
    #   env:
    #     DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
    #     DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        
#     - name: Cluster and DOP cleanup
#       run: |
#         helm uninstall kubera 
#         kubectl delete pvc --all
#         kubectl delete ns maya-system
#         eksctl delete cluster --name=test
#         eksctl get cluster --region=us-east-2
#       if: always()
        
