
name: Testing
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
        curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
        sudo mv /tmp/eksctl /usr/local/bin
        sleep 10
        eksctl version
        eksctl create cluster --name=test
        kubectl get nodes -owide
        eksctl delete cluster --name=test 
        

        
